version: '3.8'
services:
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    depends_on:
      - redis
    
  redis:
    image: redis:alpine

  static:
    build: ./static
    ports:
      - "8080:80"

  proxy:
    build: ./proxy
    ports: 
      - "80:80"
    depends_on:
      - flask
      - static
